INFO:root:/start
INFO:root:kek
INFO:root:1 kek
INFO:root:ehseak
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start
INFO:root:/start
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "bot.py", line 13, in start
    text=cfg.HELP, parse_mode=telegram.ParseMode.MARKDOWN)
NameError: name 'telegram' is not defined
INFO:root:/start or /help
ERROR:telegram.ext.dispatcher:No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 372, in process_update
    handler.handle_update(update, self, check, context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telegram/ext/handler.py", line 117, in handle_update
    return self.callback(update, context)
  File "bot.py", line 13, in start
    text=cfg.HELP, parse_mode=telegram.ParseMode.MARKDOWN)
NameError: name 'telegram' is not defined
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:/start or /help
INFO:root:/show_list
INFO:root:/show_list
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:1 кек
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
